version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    allow:
      - dependency-type: all
    cooldown:
      default-days: 7
    groups:
      gems:
        patterns: ['*']
        update-types: [minor, patch]
    labels: [skip-changelog]
    commit-message:
      prefix: chore(deps)
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    labels: [skip-changelog]
    commit-message:
      prefix: ci
